baseURL: "http://cropsnleaves.net/"
languageCode: en-us
title: Lakshmanan Venkatesan
theme: PaperMod
googleAnalytics: G-68NX9FKNLJ

permalinks:
  posts: "/:slug"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  defaultTheme: auto
  ShowReadingTime: true
  ShowCodeCopyButtons: true

  homeInfoParams:
    FirstParagraph: >
      Howdy! I am Lakshmanan, Software Engineer with focus on location techologies and cloud computing.
      I work on digital phenotyping involves the use of advanced technologies, such as remote sensing, computer vision, and machine learning.
       
    Title: Lakshmanan Venkatesan    
  socialIcons:
    - name: email
      url: "mailto:laksh.gisprog@gmail.com"
    - name: github
      url: "https://github.com/iamlaksh1"
    - name: twitter
      url: "https://twitter.com/iamlaksh1"



menu:
  main:
    - name: Posts
      pageRef: /posts/
      weight: 2 
    - identifier: GitHub
      name: GitHub
      url: "https://github.com/iamlaksh1"
      weight: 3